# Server
server: 
  port: 80
#server.servlet.context-path=/ssafy

# DataSource
spring:
#  application:
#    name: enjoytrip
  datasource: 
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&allowMultiQueries=true
    hikari: 
      username: ssafy
      password: ssafy
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  mvc: # Swagger
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    
# Mybatis
mybatis:
  mapper-locations: mappers/*/*.xml
  type-aliases-package: com.ssafy.enjoytrip.*.model.dto

logging:
  level: 
    com.ssafy: debug

